"use strict";

const activities = {
  businesses: [
    {
      id: "XlMMUoGIOhIE-aWRXgTd1A",
      alias: "musée-d-orsay-paris-3",
      name: "Musée d’Orsay",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/KQ8by6238o2q6tH59Kfasg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/mus%C3%A9e-d-orsay-paris-3?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 836,
      categories: [
        {
          alias: "museums",
          title: "Museums",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8604072252412,
        longitude: 2.32502393267818,
      },
      transactions: [],
      location: {
        address1: "1 rue de la Légion d'Honneur",
        address2: null,
        address3: null,
        city: "Paris",
        zip_code: "75007",
        country: "FR",
        state: "75",
        display_address: [
          "1 rue de la Légion d'Honneur",
          "75007 Paris",
          "France",
        ],
      },
      phone: "+33140494814",
      display_phone: "+33 1 40 49 48 14",
      distance: 1242.5926257335125,
    },
    {
      id: "In3z-xigGXnYXlBS-mhOPg",
      alias: "la-tour-eiffel-paris-4",
      name: "La Tour Eiffel",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/yC2QWLAWIWDJy8OdxVbBwA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/la-tour-eiffel-paris-4?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 1974,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.858368,
        longitude: 2.29448028497734,
      },
      transactions: [],
      location: {
        address1: "5 avenue Anatole France",
        address2: "",
        address3: "Champ de Mars",
        city: "Paris",
        zip_code: "75007",
        country: "FR",
        state: "75",
        display_address: [
          "5 avenue Anatole France",
          "Champ de Mars",
          "75007 Paris",
          "France",
        ],
      },
      phone: "+33892701239",
      display_phone: "+33 892 70 12 39",
      distance: 3509.898735052554,
    },
    {
      id: "W5gfGdQQlxvPsbEKCfiMhA",
      alias: "bike-about-tours-paris",
      name: "Bike About Tours",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/O8SqTcpjcqSFeodsxNBt2A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/bike-about-tours-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 60,
      categories: [
        {
          alias: "tours",
          title: "Tours",
        },
        {
          alias: "bikerentals",
          title: "Bike Rentals",
        },
      ],
      rating: 5,
      coordinates: {
        latitude: 48.855544,
        longitude: 2.355904,
      },
      transactions: [],
      location: {
        address1: "17 rue du Pont Louis Philippe",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75004",
        country: "FR",
        state: "75",
        display_address: [
          "17 rue du Pont Louis Philippe",
          "75004 Paris",
          "France",
        ],
      },
      phone: "+33618808492",
      display_phone: "+33 6 18 80 84 92",
      distance: 1233.4978755217273,
    },
    {
      id: "AIFm9k7TzVrPdDs5PqAKwQ",
      alias: "secret-food-tours-paris-4",
      name: "Secret Food Tours",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/mSnE_g0j5sXVoKEz07YE7Q/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/secret-food-tours-paris-4?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 59,
      categories: [
        {
          alias: "foodtours",
          title: "Food Tours",
        },
      ],
      rating: 5,
      coordinates: {
        latitude: 48.8829653343873,
        longitude: 2.34421818829958,
      },
      transactions: [],
      location: {
        address1: "",
        address2: null,
        address3: "",
        city: "Paris",
        zip_code: "",
        country: "FR",
        state: "75",
        display_address: ["Paris", "France"],
      },
      phone: "+33970735298",
      display_phone: "+33 9 70 73 52 98",
      distance: 2340.7416723284496,
    },
    {
      id: "qq-0DAkiLPJivqCJff6nFw",
      alias: "musée-du-louvre-paris-2",
      name: "Musée du Louvre",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/_l78eImQu1vJurtwF9rIZQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/mus%C3%A9e-du-louvre-paris-2?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 1845,
      categories: [
        {
          alias: "museums",
          title: "Museums",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.86206,
        longitude: 2.334521,
      },
      transactions: [],
      location: {
        address1: "Place du Carrousel",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75001",
        country: "FR",
        state: "75",
        display_address: ["Place du Carrousel", "75001 Paris", "France"],
      },
      phone: "+33140205050",
      display_phone: "+33 1 40 20 50 50",
      distance: 558.0335061024725,
    },
    {
      id: "2U00N6efcaeHQuzyWVzKdQ",
      alias: "opéra-national-de-paris-palais-garnier-paris",
      name: "Opéra National de Paris - Palais Garnier",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/tSxrQBXy-ZrV_JcfRlw1xw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/op%C3%A9ra-national-de-paris-palais-garnier-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 237,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
        {
          alias: "opera",
          title: "Opera & Ballet",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8719444,
        longitude: 2.3316667,
      },
      transactions: [],
      location: {
        address1: "8 rue Scribe",
        address2: "",
        address3: null,
        city: "Paris",
        zip_code: "75009",
        country: "FR",
        state: "75",
        display_address: ["8 rue Scribe", "75009 Paris", "France"],
      },
      phone: "+33171252423",
      display_phone: "+33 1 71 25 24 23",
      distance: 1349.317717870548,
    },
    {
      id: "59t0GoHQBACyUX22iUQ03w",
      alias: "jardin-du-luxembourg-paris",
      name: "Jardin du Luxembourg",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/7A0YoURe_2xMgLVN2BoOig/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/jardin-du-luxembourg-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 367,
      categories: [
        {
          alias: "parks",
          title: "Parks",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8468096948025,
        longitude: 2.33754648154959,
      },
      transactions: [],
      location: {
        address1: "Rue de Médicis",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75006",
        country: "FR",
        state: "75",
        display_address: ["Rue de Médicis", "75006 Paris", "France"],
      },
      phone: "+33140717560",
      display_phone: "+33 1 40 71 75 60",
      distance: 1717.7913481019966,
    },
    {
      id: "jwkx74KO5nLgkYmDj59IdA",
      alias: "fat-tire-tours-paris-3",
      name: "Fat Tire Tours",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/iB8fj0U81DV24vpi5pLPjQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/fat-tire-tours-paris-3?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 217,
      categories: [
        {
          alias: "biketours",
          title: "Bike tours",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.852099,
        longitude: 2.295222,
      },
      transactions: [],
      location: {
        address1: "24 rue Edgar Faure",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75015",
        country: "FR",
        state: "75",
        display_address: ["24 rue Edgar Faure", "75015 Paris", "France"],
      },
      phone: "+33182888096",
      display_phone: "+33 1 82 88 80 96",
      distance: 3603.877812210703,
    },
    {
      id: "dfiOVKCTnsufmStVL0b5cg",
      alias: "l-arc-de-triomphe-paris-5",
      name: "L'Arc de Triomphe",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/MlrwnK91cU8o2gu3Wncv0A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/l-arc-de-triomphe-paris-5?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 664,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8738256014877,
        longitude: 2.29502221103758,
      },
      transactions: [],
      location: {
        address1: "Place de l'Étoile",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75008",
        country: "FR",
        state: "75",
        display_address: ["Place de l'Étoile", "75008 Paris", "France"],
      },
      phone: "+33155377377",
      display_phone: "+33 1 55 37 73 77",
      distance: 3690.880795494037,
    },
    {
      id: "spIGAtquYQ0S7xai5eJSuA",
      alias: "basilique-du-sacré-cœur-de-montmartre-paris-3",
      name: "Basilique du Sacré-Cœur de Montmartre",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/kji7hJrPlkh3aoYzOXl3YQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/basilique-du-sacr%C3%A9-c%C5%93ur-de-montmartre-paris-3?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 582,
      categories: [
        {
          alias: "churches",
          title: "Churches",
        },
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.88709,
        longitude: 2.34343,
      },
      transactions: [],
      location: {
        address1: "35 rue du Chevalier de la Barre",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75018",
        country: "FR",
        state: "75",
        display_address: [
          "35 rue du Chevalier de la Barre",
          "75018 Paris",
          "France",
        ],
      },
      phone: "+33153418900",
      display_phone: "+33 1 53 41 89 00",
      distance: 2753.1050171821244,
    },
    {
      id: "chEk0cD3XPqjB13FBdISmg",
      alias: "la-cuisine-paris-paris",
      name: "La Cuisine Paris",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/okBAVYDfAIRroc4Pybd-EA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/la-cuisine-paris-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 83,
      categories: [
        {
          alias: "foodtours",
          title: "Food Tours",
        },
        {
          alias: "cookingclasses",
          title: "Cooking Classes",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8547,
        longitude: 2.35413,
      },
      transactions: [],
      price: "€€",
      location: {
        address1: "80 quai de l'Hôtel de Ville",
        address2: null,
        address3: null,
        city: "Paris",
        zip_code: "75004",
        country: "FR",
        state: "75",
        display_address: [
          "80 quai de l'Hôtel de Ville",
          "75004 Paris",
          "France",
        ],
      },
      phone: "+33961499795",
      display_phone: "+33 9 61 49 97 95",
      distance: 1191.573382231037,
    },
    {
      id: "DlYDIO3PghloMFqR555AXQ",
      alias: "paris-by-scooter-paris",
      name: "Paris by Scooter",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/1cx_gPcK9Iijv92TvNkM7g/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/paris-by-scooter-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 19,
      categories: [
        {
          alias: "scooterrentals",
          title: "Scooter Rentals",
        },
        {
          alias: "scootertours",
          title: "Scooter Tours",
        },
      ],
      rating: 5,
      coordinates: {
        latitude: 48.8717329,
        longitude: 2.3240243,
      },
      transactions: [],
      location: {
        address1: "16 rue de l'Arcade",
        address2: null,
        address3: "",
        city: "Paris",
        zip_code: "75008",
        country: "FR",
        state: "75",
        display_address: ["16 rue de l'Arcade", "75008 Paris", "France"],
      },
      phone: "+33628353930",
      display_phone: "+33 6 28 35 39 30",
      distance: 1714.231268588624,
    },
    {
      id: "nLhucP559heMITREThEWcw",
      alias: "île-de-la-cité-paris-4",
      name: "Île de la Cité",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/1wUys_M9v6bdy3MFVy9kjQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/%C3%AEle-de-la-cit%C3%A9-paris-4?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 63,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.855169,
        longitude: 2.346676,
      },
      transactions: [],
      location: {
        address1: "",
        address2: null,
        address3: null,
        city: "Paris",
        zip_code: "75004",
        country: "FR",
        state: "75",
        display_address: ["75004 Paris", "France"],
      },
      phone: "",
      display_phone: "",
      distance: 824.4496536016235,
    },
    {
      id: "ylO0kyFugviHy71AGbxvRw",
      alias: "le-parc-des-buttes-chaumont-paris",
      name: "Le Parc des Buttes Chaumont",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/nhXgAcg3aJdGae68BYxEyw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/le-parc-des-buttes-chaumont-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 183,
      categories: [
        {
          alias: "parks",
          title: "Parks",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8769112,
        longitude: 2.3810999,
      },
      transactions: [],
      location: {
        address1: "1 rue Botzaris",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75019",
        country: "FR",
        state: "75",
        display_address: ["1 rue Botzaris", "75019 Paris", "France"],
      },
      phone: "",
      display_phone: "",
      distance: 3299.06764308251,
    },
    {
      id: "g0FWW7QvkyuEt_8EnYF7BA",
      alias: "musée-albert-kahn-boulogne-billancourt-3",
      name: "Musée Albert Kahn",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/r0b_6iWF0qaGxxOvV1UfWQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/mus%C3%A9e-albert-kahn-boulogne-billancourt-3?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 52,
      categories: [
        {
          alias: "gardens",
          title: "Botanical Gardens",
        },
        {
          alias: "museums",
          title: "Museums",
        },
        {
          alias: "parks",
          title: "Parks",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.84136,
        longitude: 2.22748,
      },
      transactions: [],
      location: {
        address1: "14 rue du Port",
        address2: "",
        address3: "",
        city: "Boulogne-billancourt",
        zip_code: "92100",
        country: "FR",
        state: "92",
        display_address: [
          "14 rue du Port",
          "92100 Boulogne-billancourt",
          "France",
        ],
      },
      phone: "+33155192800",
      display_phone: "+33 1 55 19 28 00",
      distance: 8690.544890427616,
    },
    {
      id: "cBMBn_yVCzq3pOmtWgY99Q",
      alias: "montmartre-paris-4",
      name: "Montmartre",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/3a3XwaiJWn6em2-oNRsY8A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/montmartre-paris-4?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 98,
      categories: [
        {
          alias: "localflavor",
          title: "Local Flavor",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.886198,
        longitude: 2.343089,
      },
      transactions: [],
      location: {
        address1: "",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75018",
        country: "FR",
        state: "75",
        display_address: ["75018 Paris", "France"],
      },
      phone: "",
      display_phone: "",
      distance: 2696.173336632859,
    },
    {
      id: "rsMCCV92ozqi_OexnvWs3g",
      alias: "left-bank-scooters-paris-5",
      name: "Left Bank Scooters",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/x1HDSdPZG26jGEVsifXAyA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/left-bank-scooters-paris-5?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 29,
      categories: [
        {
          alias: "scooterrentals",
          title: "Scooter Rentals",
        },
        {
          alias: "scootertours",
          title: "Scooter Tours",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8683452747277,
        longitude: 2.33037591864627,
      },
      transactions: [],
      location: {
        address1: "Rue de la Paix",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75002",
        country: "FR",
        state: "75",
        display_address: ["Rue de la Paix", "75002 Paris", "France"],
      },
      phone: "+33678120424",
      display_phone: "+33 6 78 12 04 24",
      distance: 1116.1564052374717,
    },
    {
      id: "-RkDwNPPWOYestnNH_877Q",
      alias: "jardin-des-tuileries-paris-2",
      name: "Jardin des Tuileries",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/_MKui5gvmsNmTIqHqIAlHw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/jardin-des-tuileries-paris-2?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 224,
      categories: [
        {
          alias: "parks",
          title: "Parks",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 48.863396,
        longitude: 2.327307,
      },
      transactions: [],
      location: {
        address1: "113 rue de Rivoli",
        address2: "",
        address3: null,
        city: "Paris",
        zip_code: "75001",
        country: "FR",
        state: "75",
        display_address: ["113 rue de Rivoli", "75001 Paris", "France"],
      },
      phone: "+33140209043",
      display_phone: "+33 1 40 20 90 43",
      distance: 1097.3278958761105,
    },
    {
      id: "gQgujgqGepUXNIcnvpcwQw",
      alias: "les-catacombes-de-paris-paris",
      name: "Les Catacombes de Paris",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/i3UlOx313vUE1iNEVR7Mlg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/les-catacombes-de-paris-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 408,
      categories: [
        {
          alias: "localflavor",
          title: "Local Flavor",
        },
        {
          alias: "museums",
          title: "Museums",
        },
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 48.833838,
        longitude: 2.332422,
      },
      transactions: [],
      location: {
        address1: "1 avenue du Colonel Henri Rol-Tanguy",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75014",
        country: "FR",
        state: "75",
        display_address: [
          "1 avenue du Colonel Henri Rol-Tanguy",
          "75014 Paris",
          "France",
        ],
      },
      phone: "+33143224763",
      display_phone: "+33 1 43 22 47 63",
      distance: 3206.8296453870075,
    },
    {
      id: "SfeBa1C_dfdBNcn6DYCOOw",
      alias: "musée-des-arts-forains-les-pavillons-de-bercy-paris",
      name: "Musée des Arts Forains - Les Pavillons de Bercy",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/mNO8CLT1PdJAwt0m3Qdv2g/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/mus%C3%A9e-des-arts-forains-les-pavillons-de-bercy-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 38,
      categories: [
        {
          alias: "museums",
          title: "Museums",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.83243508,
        longitude: 2.3890405,
      },
      transactions: [],
      location: {
        address1: "53 avenue des Terroirs de France",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75012",
        country: "FR",
        state: "75",
        display_address: [
          "53 avenue des Terroirs de France",
          "75012 Paris",
          "France",
        ],
      },
      phone: "+33143401622",
      display_phone: "+33 1 43 40 16 22",
      distance: 4748.804287738719,
    },
  ],
  total: 3400,
  region: {
    center: {
      longitude: 2.3421478271484375,
      latitude: 48.86195860677958,
    },
  },
};

const sights = {
  businesses: [
    {
      id: "S329otki_aHyanlMlfkYxg",
      alias: "wego-walking-tours-paris",
      name: "Wego Walking Tours",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/UnWTMY7ekd5ucAzy4BtOhA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/wego-walking-tours-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 37,
      categories: [
        {
          alias: "walkingtours",
          title: "Walking Tours",
        },
      ],
      rating: 5,
      coordinates: {
        latitude: 48.85242,
        longitude: 2.3483,
      },
      transactions: [],
      location: {
        address1: "Pont au Double",
        address2: null,
        address3: "",
        city: "Paris",
        zip_code: "75005",
        country: "FR",
        state: "75",
        display_address: ["Pont au Double", "75005 Paris", "France"],
      },
      phone: "",
      display_phone: "",
      distance: 1138.396470534434,
    },
    {
      id: "In3z-xigGXnYXlBS-mhOPg",
      alias: "la-tour-eiffel-paris-4",
      name: "La Tour Eiffel",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/yC2QWLAWIWDJy8OdxVbBwA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/la-tour-eiffel-paris-4?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 1974,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.858368,
        longitude: 2.29448028497734,
      },
      transactions: [],
      location: {
        address1: "5 avenue Anatole France",
        address2: "",
        address3: "Champ de Mars",
        city: "Paris",
        zip_code: "75007",
        country: "FR",
        state: "75",
        display_address: [
          "5 avenue Anatole France",
          "Champ de Mars",
          "75007 Paris",
          "France",
        ],
      },
      phone: "+33892701239",
      display_phone: "+33 892 70 12 39",
      distance: 3509.898735052554,
    },
    {
      id: "qq-0DAkiLPJivqCJff6nFw",
      alias: "musée-du-louvre-paris-2",
      name: "Musée du Louvre",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/_l78eImQu1vJurtwF9rIZQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/mus%C3%A9e-du-louvre-paris-2?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 1845,
      categories: [
        {
          alias: "museums",
          title: "Museums",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.86206,
        longitude: 2.334521,
      },
      transactions: [],
      location: {
        address1: "Place du Carrousel",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75001",
        country: "FR",
        state: "75",
        display_address: ["Place du Carrousel", "75001 Paris", "France"],
      },
      phone: "+33140205050",
      display_phone: "+33 1 40 20 50 50",
      distance: 558.0335061024725,
    },
    {
      id: "2U00N6efcaeHQuzyWVzKdQ",
      alias: "opéra-national-de-paris-palais-garnier-paris",
      name: "Opéra National de Paris - Palais Garnier",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/tSxrQBXy-ZrV_JcfRlw1xw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/op%C3%A9ra-national-de-paris-palais-garnier-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 237,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
        {
          alias: "opera",
          title: "Opera & Ballet",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8719444,
        longitude: 2.3316667,
      },
      transactions: [],
      location: {
        address1: "8 rue Scribe",
        address2: "",
        address3: null,
        city: "Paris",
        zip_code: "75009",
        country: "FR",
        state: "75",
        display_address: ["8 rue Scribe", "75009 Paris", "France"],
      },
      phone: "+33171252423",
      display_phone: "+33 1 71 25 24 23",
      distance: 1349.317717870548,
    },
    {
      id: "Pl2Wv3d8WlrDJRym8m_2gg",
      alias: "musée-de-l-orangerie-paris-2",
      name: "Musée de l’Orangerie",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/W8JGOsZMFo25wQQTJUzY9A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/mus%C3%A9e-de-l-orangerie-paris-2?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 219,
      categories: [
        {
          alias: "museums",
          title: "Museums",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.863791,
        longitude: 2.322667,
      },
      transactions: [],
      location: {
        address1: "Place de la Concorde",
        address2: "",
        address3: "Jardin des Tuileries",
        city: "Paris",
        zip_code: "75001",
        country: "FR",
        state: "75",
        display_address: [
          "Place de la Concorde",
          "Jardin des Tuileries",
          "75001 Paris",
          "France",
        ],
      },
      phone: "+33144778007",
      display_phone: "+33 1 44 77 80 07",
      distance: 1439.5343691936946,
    },
    {
      id: "59t0GoHQBACyUX22iUQ03w",
      alias: "jardin-du-luxembourg-paris",
      name: "Jardin du Luxembourg",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/7A0YoURe_2xMgLVN2BoOig/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/jardin-du-luxembourg-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 367,
      categories: [
        {
          alias: "parks",
          title: "Parks",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8468096948025,
        longitude: 2.33754648154959,
      },
      transactions: [],
      location: {
        address1: "Rue de Médicis",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75006",
        country: "FR",
        state: "75",
        display_address: ["Rue de Médicis", "75006 Paris", "France"],
      },
      phone: "+33140717560",
      display_phone: "+33 1 40 71 75 60",
      distance: 1717.7913481019966,
    },
    {
      id: "dfiOVKCTnsufmStVL0b5cg",
      alias: "l-arc-de-triomphe-paris-5",
      name: "L'Arc de Triomphe",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/MlrwnK91cU8o2gu3Wncv0A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/l-arc-de-triomphe-paris-5?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 664,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8738256014877,
        longitude: 2.29502221103758,
      },
      transactions: [],
      location: {
        address1: "Place de l'Étoile",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75008",
        country: "FR",
        state: "75",
        display_address: ["Place de l'Étoile", "75008 Paris", "France"],
      },
      phone: "+33155377377",
      display_phone: "+33 1 55 37 73 77",
      distance: 3690.880795494037,
    },
    {
      id: "spIGAtquYQ0S7xai5eJSuA",
      alias: "basilique-du-sacré-cœur-de-montmartre-paris-3",
      name: "Basilique du Sacré-Cœur de Montmartre",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/kji7hJrPlkh3aoYzOXl3YQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/basilique-du-sacr%C3%A9-c%C5%93ur-de-montmartre-paris-3?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 582,
      categories: [
        {
          alias: "churches",
          title: "Churches",
        },
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.88709,
        longitude: 2.34343,
      },
      transactions: [],
      location: {
        address1: "35 rue du Chevalier de la Barre",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75018",
        country: "FR",
        state: "75",
        display_address: [
          "35 rue du Chevalier de la Barre",
          "75018 Paris",
          "France",
        ],
      },
      phone: "+33153418900",
      display_phone: "+33 1 53 41 89 00",
      distance: 2753.1050171821244,
    },
    {
      id: "vGbC1fqOEGbK-eLLYN6U_w",
      alias: "musée-rodin-paris-3",
      name: "Musée Rodin",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/arGkGfuUvqPHQpcxR-9jZQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/mus%C3%A9e-rodin-paris-3?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 260,
      categories: [
        {
          alias: "museums",
          title: "Museums",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.855308,
        longitude: 2.315834,
      },
      transactions: [],
      location: {
        address1: "77 rue de Varenne",
        address2: null,
        address3: null,
        city: "Paris",
        zip_code: "75007",
        country: "FR",
        state: "75",
        display_address: ["77 rue de Varenne", "75007 Paris", "France"],
      },
      phone: "+33144186110",
      display_phone: "+33 1 44 18 61 10",
      distance: 2062.202692434676,
    },
    {
      id: "TRiImFeW-3igJKcUTndDtw",
      alias: "pont-alexandre-iii-paris",
      name: "Pont Alexandre III",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/lws2G64poe1CFzOLMg_9Og/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/pont-alexandre-iii-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 79,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.863985,
        longitude: 2.313596,
      },
      transactions: [],
      location: {
        address1: "Quai d'Orsay",
        address2: null,
        address3: null,
        city: "Paris",
        zip_code: "75007",
        country: "FR",
        state: "75",
        display_address: ["Quai d'Orsay", "75007 Paris", "France"],
      },
      phone: "",
      display_phone: "",
      distance: 2100.7095795368577,
    },
    {
      id: "yk4F8N3ibts5rETt-WByZQ",
      alias: "le-pont-neuf-paris",
      name: "Le Pont Neuf",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/L1k0Rcqay5zeZlcx9ruZ9A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/le-pont-neuf-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 78,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8570755667268,
        longitude: 2.34135228261721,
      },
      transactions: [],
      location: {
        address1: "",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75001",
        country: "FR",
        state: "75",
        display_address: ["75001 Paris", "France"],
      },
      phone: "",
      display_phone: "",
      distance: 546.0788247658303,
    },
    {
      id: "cBMBn_yVCzq3pOmtWgY99Q",
      alias: "montmartre-paris-4",
      name: "Montmartre",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/3a3XwaiJWn6em2-oNRsY8A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/montmartre-paris-4?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 98,
      categories: [
        {
          alias: "localflavor",
          title: "Local Flavor",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.886198,
        longitude: 2.343089,
      },
      transactions: [],
      location: {
        address1: "",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75018",
        country: "FR",
        state: "75",
        display_address: ["75018 Paris", "France"],
      },
      phone: "",
      display_phone: "",
      distance: 2696.173336632859,
    },
    {
      id: "zHk-T7hg6ASn4raTFiZ1wA",
      alias: "hôtel-des-invalides-paris-3",
      name: "Hôtel des Invalides",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/5Gk17Zn9ZHE_CT2qgkd3AQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/h%C3%B4tel-des-invalides-paris-3?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 77,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
        {
          alias: "museums",
          title: "Museums",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8550060555776,
        longitude: 2.31247186692645,
      },
      transactions: [],
      location: {
        address1: "Esplanade des Invalides",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75007",
        country: "FR",
        state: "75",
        display_address: ["Esplanade des Invalides", "75007 Paris", "France"],
      },
      phone: "+33810113399",
      display_phone: "+33 810 11 33 99",
      distance: 2304.555575086466,
    },
    {
      id: "rsMCCV92ozqi_OexnvWs3g",
      alias: "left-bank-scooters-paris-5",
      name: "Left Bank Scooters",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/x1HDSdPZG26jGEVsifXAyA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/left-bank-scooters-paris-5?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 29,
      categories: [
        {
          alias: "scooterrentals",
          title: "Scooter Rentals",
        },
        {
          alias: "scootertours",
          title: "Scooter Tours",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8683452747277,
        longitude: 2.33037591864627,
      },
      transactions: [],
      location: {
        address1: "Rue de la Paix",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75002",
        country: "FR",
        state: "75",
        display_address: ["Rue de la Paix", "75002 Paris", "France"],
      },
      phone: "+33678120424",
      display_phone: "+33 6 78 12 04 24",
      distance: 1116.1564052374717,
    },
    {
      id: "eHb68tjtnrTIs3dVnQbEVA",
      alias: "le-pont-des-arts-paris-2",
      name: "Le Pont des Arts",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/8bnuTkeX55MBALPHaXpu9g/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/le-pont-des-arts-paris-2?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 137,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.85886,
        longitude: 2.33781,
      },
      transactions: [],
      location: {
        address1: "Pont des Arts",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75001",
        country: "FR",
        state: "75",
        display_address: ["Pont des Arts", "75001 Paris", "France"],
      },
      phone: "",
      display_phone: "",
      distance: 464.62520078592206,
    },
    {
      id: "gQgujgqGepUXNIcnvpcwQw",
      alias: "les-catacombes-de-paris-paris",
      name: "Les Catacombes de Paris",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/i3UlOx313vUE1iNEVR7Mlg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/les-catacombes-de-paris-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 408,
      categories: [
        {
          alias: "localflavor",
          title: "Local Flavor",
        },
        {
          alias: "museums",
          title: "Museums",
        },
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 48.833838,
        longitude: 2.332422,
      },
      transactions: [],
      location: {
        address1: "1 avenue du Colonel Henri Rol-Tanguy",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75014",
        country: "FR",
        state: "75",
        display_address: [
          "1 avenue du Colonel Henri Rol-Tanguy",
          "75014 Paris",
          "France",
        ],
      },
      phone: "+33143224763",
      display_phone: "+33 1 43 22 47 63",
      distance: 3206.8296453870075,
    },
    {
      id: "HWlWSWRxrq8afV6qdTIHhQ",
      alias: "la-seine-paris-paris",
      name: "La Seine - Paris",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/rooRMRcxHCiC3_KWky7oWA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/la-seine-paris-paris?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 42,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8633766174316,
        longitude: 2.33371090888977,
      },
      transactions: [],
      location: {
        address1: null,
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75001",
        country: "FR",
        state: "75",
        display_address: ["75001 Paris", "France"],
      },
      phone: "",
      display_phone: "",
      distance: 844.2623997825217,
    },
    {
      id: "maI_y0xmhJ_zrgwE_uLEyg",
      alias: "petit-palais-paris-3",
      name: "Petit Palais",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/LuQMMixqv4YUHybv9u4mxg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/petit-palais-paris-3?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 67,
      categories: [
        {
          alias: "museums",
          title: "Museums",
        },
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.866054,
        longitude: 2.314589,
      },
      transactions: [],
      location: {
        address1: "Avenue Winston Churchill",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75008",
        country: "FR",
        state: "75",
        display_address: ["Avenue Winston Churchill", "75008 Paris", "France"],
      },
      phone: "+33153434000",
      display_phone: "+33 1 53 43 40 00",
      distance: 2066.7049836770907,
    },
    {
      id: "RcoS2n_XnjOpFtt_p5YJmA",
      alias: "le-panthéon-paris-3",
      name: "Le Panthéon",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/KuDnr5Wv8w0z_UDKIVGsvw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/le-panth%C3%A9on-paris-3?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 125,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 48.8462173157838,
        longitude: 2.3460662404786,
      },
      transactions: [],
      location: {
        address1: "Place du Panthéon",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75005",
        country: "FR",
        state: "75",
        display_address: ["Place du Panthéon", "75005 Paris", "France"],
      },
      phone: "+33144321801",
      display_phone: "+33 1 44 32 18 01",
      distance: 1773.672237495131,
    },
    {
      id: "rXDNZ6bNFs6Qh7k4alaBJw",
      alias: "rue-montorgueil-paris-3",
      name: "Rue Montorgueil",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/odwzmA7JL3M_Wg8jStGKBQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/rue-montorgueil-paris-3?adjust_creative=DTtLSFbl_eDBDPgEF5M4MA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DTtLSFbl_eDBDPgEF5M4MA",
      review_count: 29,
      categories: [
        {
          alias: "landmarks",
          title: "Landmarks & Historical Buildings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 48.8656111005854,
        longitude: 2.34700798988342,
      },
      transactions: [],
      location: {
        address1: "",
        address2: "",
        address3: "",
        city: "Paris",
        zip_code: "75002",
        country: "FR",
        state: "75",
        display_address: ["75002 Paris", "France"],
      },
      phone: "",
      display_phone: "",
      distance: 539.7613172310257,
    },
  ],
  total: 331,
  region: {
    center: {
      longitude: 2.3421478271484375,
      latitude: 48.86195860677958,
    },
  },
};

let uniquePlacesList = [];

activities.businesses.forEach((business) => {
  if (!uniquePlacesList.includes(business.name)) {
    uniquePlacesList.push([
      business.name,
      business.rating,
      business.categories[0].title,
    ]);
  }
});

sights.businesses.forEach((business) => {
  if (!uniquePlacesList.includes(business.name)) {
    uniquePlacesList.push([
      business.name,
      business.rating,
      business.categories[0].title,
    ]);
  }
});

uniquePlacesList = uniquePlacesList.sort((a, b) => b[1] - a[1]);
console.log(uniquePlacesList);
